pipeline:
  name: Build golang-example-app
  identifier: Build_wasptree_golang_example_app_1743075844326
  projectIdentifier: Andy_Sutcliffe
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Build Go App
                  identifier: build_go_app
                  spec:
                    command: |-
                      echo "Welcome to Harness CI"
                      make install
                      make test
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: wasptree/golang-example-app
        build: <+input>
